### ISSUE TITLE
Subsections and the hide from menu setting

### ISSUE THREAD

**Issue by mrleemon** [Indexhibit/indexhibit#11]
I've found that if you hide an exhibit inside a subsection from the menu, the exhibit it's also hidden from the visual index view, which makes no sense. I've found that the culprit is the `AND hidden != '1'` from this query (line 162) that can be found in the `/ndxzstudio/lib/filesourcesubsection.php` file:

```
$imgs = $OBJ->db->fetchArray("SELECT * 
              FROM ".PX."media, ".PX."objects_prefs, ".PX."objects  
	      WHERE media_ref_id = id 
	      AND section_id = '" . $OBJ->vars->exhibit['section_id'] . "'  
	      AND section_sub = '" . $OBJ->vars->exhibit['section_sub'] . "' 
	      AND subdir = '0' 
	      AND media_mime IN ('" . implode('\', \'', $this->medias) . "') 
	      AND media_order = (SELECT MIN(media_order) FROM ".PX."media WHERE media_ref_id = id)  
	      AND section_top != '1'   
	      AND status = '1' 
              AND hidden != '1'
	      GROUP BY id 
	      ORDER BY ord ASC");
```

If I remove this condition, the exhibit is not hidden from the visual index view.

**Comment by Vaska** [comment]
I can understand that, but a hidden exhibit is a hidden exhibit - it's working as it was designed. Hidden exhibits, the thought process, was that you would either send this link directly to somebody or you would link to it from another page. You are more than welcome to customize this to do what you want. Actually, the way I would go about customizing this would be to rewrite the query(ies) directly in a custom exhibit format. ;)

**Comment by Vaska** [comment]
That's true! That was created before Visual Index even existed (which is an 'index' btw). But, it's always been that way...guess we should update that string (that's the real bug here).
