### ISSUE TITLE
500 Internal Server Error when trying to enable the Tag Display format in 2.1.5.

### ISSUE THREAD

**Issue by mrleemon** [Indexhibit/indexhibit#12]
It's impossible to enable the Tag Display format in 2.1.5.
The server returns a 500 Internal Server Error.

**Comment by Vaska** [comment]
We have a forum for general problems.

**Comment by mrleemon** [comment]
https://www.indexhibit.org/forum/thread/23154/

**Comment by mrleemon** [comment]
It seems it's not a general problem but a bug in the file `format.tag_display.php` file. There are two instances of the `__construct()` function, and one is empty. Removing this one the problem is fixed:

```
public function __construct()
{
}
```
The file also contains a `Exhibit()` function which I think you deprecated from every class in the 2.1.5 release.

**Comment by Vaska** [comment]
Thanks for catching that - already fixed on the files here...
