### ISSUE TITLE
Update from early version to newest

### ISSUE THREAD

**Issue by jrtderonde** [Indexhibit/indexhibit#13]
Hey,

I came across a migration problem which I fixed with replacing `$page = '';` to `$page = [];` on lines 1049 and 1088 of `install.php`

**Comment by jrtderonde** [comment]
After this change, the upgrade went smooth. Maybe you want to look into updating from very early versions to the newest with the end of life of PHP 5.x in the near future.

**Comment by Indexhibit** [comment]
Thanks for the note - fixed in latest update.
