### ISSUE TITLE
Vimeo videos and SSL

### ISSUE THREAD

**Issue by mrleemon** [Indexhibit/indexhibit#14]
I installed an SSL certificate on my site and mostly everything is working as expected, except Vimeo videos uploaded to exhibits because of mixed content issues.

You should change the following IFRAME code to use https instead of plain http on line 228 in the `plugin.formats.php` file:

`return "<div class='vimeo' style='width: {$width}px; height: {$height}px;'><iframe src='http://player.vimeo.com/video/$file' width='{$width}' height='{$height}' frameborder='0' webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div>\n";`

to:

`return "<div class='vimeo' style='width: {$width}px; height: {$height}px;'><iframe src='https://player.vimeo.com/video/$file' width='{$width}' height='{$height}' frameborder='0' webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div>\n";`

**Comment by Indexhibit** [comment]
Fixed in latest update.
