### ISSUE TITLE
Subsection bug

### ISSUE THREAD

**Issue by mrleemon** [Indexhibit/indexhibit#15]
There's a couple of bugs related to subsections in the plugin.index.php file.

In line 391, you should change:
`$active_subsection = ($flag == true) ? " class='active_subsection'" : '';`
to:
`$active_subsection = ($flag == true) ? " active_subsection" : '';`

In line 534, you should change:
`$active_subsection = ($flag == true) ? " class='active_subsection'" : '';`
to:
`$active_subsection = ($flag == true) ? " active_subsection" : '';`

**Comment by Indexhibit** [comment]
Thanks for the note - just fixed this. ;)
