### ISSUE TITLE
Check if variable tmp is defined

### ISSUE THREAD

**Issue by theleemon** [Indexhibit/indexhibit#2]
In the `makeNodes()` function in the `/ndxzsite/js/jquery.ndxzbox.js` file, you should check if the variable tmp is defined before using it. Not doing this, sometimes it breaks other JS scripts:

```
function makeNodes() {
    var count = 0;
    $('.picture_holder a').each(function()
    {    
        var tmp = $(this).attr('id');
        if (tmp) {
            node[count] = tmp.replace('aaa', '');
            count++;
        }
    });
}

```

**Comment by Indexhibit** [comment]
Fixed. Thanks for pointing this out. Vaska
