### ISSUE TITLE
Reflected Cross Site Scripting(XSS)-/ndxzsite/plugin/ajax.php

### ISSUE THREAD

**Issue by zyfyc** [Indexhibit/indexhibit#20]
In page localhost//ndxzsite/plugin/ajax.php, the POST function can change the function used in PHP, the user/attacker can modify the parament and add the script which will be shown without filtering. They can use the script to steal the cookie or some things worse.
Payload used:
 jxs=slideshow&i=0&z=`<img src="a" onerror=alert(1)>&z=<img src="a" onerror=alert(2)>`
Affected URL: http://localhost//ndxzsite/plugin/ajax.php
so,when we visit this url:localhost//ndxzsite/plugin/ajax.php and POST data:
 jxs=slideshow&i=0&z=`<img src="a" onerror=alert(1)>&z=<img src="a" onerror=alert(2)>`
The js will executes.

![y3db2 e7 n5sr o30g5a 8](https://user-images.githubusercontent.com/43108927/52912796-83b9a680-32f1-11e9-8e86-14d1c069410c.png)

**Comment by Vaska** [comment]
Fixed.
