### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by jferard** [Indexhibit/indexhibit#23]
You don't provide any information on license under which you share the code. Can you add a `LICENSE` file and a header on every file?
If you need help to decide, I found this link: https://github.blog/2013-07-15-choosing-an-open-source-license/
(I like GPLv3 because if someone forks your project, the fork remains open source, but it's up to you to decide).

**Comment by jferard** [comment]
Some background: it's important because without a license, nobody should use, customize, or fork your code. Furthermore, coders making PR don't know what will happen to their code.

To make a long story short: it has no meaning to put your code on Github without a license.

**Comment by Vaska** [comment]
Even before being posted to Github it was, and still is, in the /ndxzstudio folder. I guess I need to move that? Anyway, I'll put it on a list of things to do...

**Comment by jferard** [comment]
My bad! You should move it to the root of the repo, so that Github (and the inattentive visitors) will detect it.
