### ISSUE TITLE
There is a file upload vulnerability

### ISSUE THREAD

**Issue by zyfyc** [Indexhibit/indexhibit#25]
There is a file upload vulnerability so that we can control the server by any account.

**Comment by Vaska** [comment]
I am trying to work on this already and could use some help - I would love to have your notes on this, as well. Feel free to send me an email at support@indexhibit.org.

**Comment by zyfyc** [comment]
ok,I will do this&nbsp;as soon as possible




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Vaska"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 下午3:43
收件人:&nbsp;"Indexhibit/indexhibit"<indexhibit@noreply.github.com&gt;;
抄送:&nbsp;"夜程"<3365487579@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Indexhibit/indexhibit] There is a file upload vulnerability (#25)




I am trying to work on this already and could use some help - I would love to have your notes on this, as well. Feel free to send me an email at support@indexhibit.org.
