### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by mrleemon** [Indexhibit/indexhibit#27]
Are there any plans to update Indexhibit to be compatible with PHP 8?
Right now, we are presented with nothing but a white screen when running it under this PHP version.

Thanks

**Comment by Indexhibit** [comment]
Yes. And, mostly very soon (assuming I don't have any more snags).

**Comment by mrleemon** [comment]
Thanks!

**Comment by CelloHubster** [comment]
Hello and thank you for the great thing that is Indexhibit. 
May I ask the same question: Is there any chance to have Indexhibit compatible with PHP 8, ideally 8.3, anytime soon?
Thanks and best regards!

**Comment by ferdinandhodl** [comment]
Is there any chance to have Indexhibit compatible with PHP 8, ideally 8.4, anytime soon?
