### ISSUE TITLE
Last version 

### ISSUE THREAD

**Issue by Pepemanuel** [Indexhibit/indexhibit#30]
Hello, 
Could someone tell me how to download the latest version?  I don't see link.  I currently have version V.2.1.5 
Thanks

**Comment by kees-** [comment]
If you don't use git via cli or desktop then go to the repo page -> green `Code` button -> Download ZIP.

You just work with the files directly since the cms has its own build routine, don't need to do intermediate source building.

As far as upgrading I won't be of help

**Comment by Pepemanuel** [comment]
Thanks for the help.  I was able to download it.  But it's not working.  Does anyone know if the code is finished?

**Comment by kees-** [comment]
If possible give details of what you tried and what's not working

**Comment by kees-** [comment]
So, troubleshoot

https://forum.indexhibit.org/tutorials/getting-started/installation/

- Check directory permissions
- Did you configure `config/config.php` file? Did you overwrite the one you had configured with a blank file?
- Check `.htaccess` file
- Find any error logs created and deposited on the server alongside the files, analyze them
- Check php version

I have no expertise and am just thinking of possibilities

**Comment by Pepemanuel** [comment]
Thank you!  I will check everything you tell me.  Yes, the archive conf.  okay, it fits my database.  
My server is on PHP 7. maybe this update only works on PHP8?

Thanks.

**Comment by kees-** [comment]
Ever updated php on your server? Do you use php for other user-installed frameworks or scripts? Even if neither it is pretty user friendly with most web hosts. Especially those providing an interface like cpanel.

Check how much was changed in the most recent diff [here](https://github.com/Indexhibit/indexhibit/commit/fb0ac9e0771745c2c555a0c2fb25b32930592d17). With how much code was updated and the hint from the commit note it is possible all version support earlier than 8 was dropped. If it would not cause breaking changes elsewhere then changing version would be first thing I'd try.

**Comment by Pepemanuel** [comment]
@yas0nia didn't work for me.  If anyone does, please report it.
