### ISSUE TITLE
Upload Error Abort

### ISSUE THREAD

**Issue by HazMatt69** [Indexhibit/indexhibit#33]
Hi,

While using latest indexhibit from Github, I can't upload files anymore. My setup is Apache with SSL & http2. Here's the log:

`[Mon Aug 29 09:16:08.824527 2022] [http2:debug] [pid 1372190:tid 140383153551104] h2_session.c(1700): [client 104.28.40.15:11869] AH03078: h2_session(149,IDLE,0): transit [BUSY] -- no io (keepalive) --> [IDLE]
[Mon Aug 29 09:16:08.824458 2022] [http2:debug] [pid 1372190:tid 140383153551104] h2_bucket_beam.c(1282): [client 104.28.40.15:11869] beam(150-17,output,closed=1,aborted=1,empty=1,buf=0): AH03385: h2_task_destroy, reuse secondary
[Mon Aug 29 09:16:08.824351 2022] [http2:debug] [pid 1372190:tid 140383153551104] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,1): sent FRAME[DATA[length=88, flags=1, stream=17, padlen=0]], frames=127/64 (r/s)
[Mon Aug 29 09:16:08.824325 2022] [http2:debug] [pid 1372190:tid 140383153551104] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,1): sent FRAME[HEADERS[length=230, hend=1, stream=17, eos=0]], frames=127/63 (r/s)
[Mon Aug 29 09:16:08.824290 2022] [http2:debug] [pid 1372190:tid 140383153551104] h2_session.c(1545): [client 104.28.40.15:11869] AH02936: h2_stream(149-17,HALF_CLOSED_REMOTE): resumed
[Mon Aug 29 09:16:08.824247 2022] [http2:debug] [pid 1372190:tid 140383153551104] h2_session.c(1390): [client 104.28.40.15:11869] AH03073: h2_stream(149-17,HALF_CLOSED_REMOTE): submit response 200, REMOTE_WINDOW_SIZE=4194304
[Mon Aug 29 09:16:08.824131 2022] [http2:debug] [pid 1372190:tid 140384978421504] h2_task.c(83): [client 104.28.40.15:11869] AH03348: h2_task(149-17): open output to GET matthewoliver.com /ndxzstudio/?a=exhibits&q=jximg&id=53
[Mon Aug 29 09:16:08.824036 2022] [deflate:debug] [pid 1372190:tid 140384978421504] mod_deflate.c(869): [client 104.28.40.15:11869] AH01384: Zlib: Compressed 72 to 70 : URL /ndxzstudio/index.php, referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.823962 2022] [proxy:debug] [pid 1372190:tid 140384978421504] proxy_util.c(2554): AH00943: FCGI: has released connection for (*:80)
[Mon Aug 29 09:16:08.819146 2022] [proxy:debug] [pid 1372190:tid 140384978421504] proxy_util.c(3188): AH02823: FCGI: connection established with Unix domain socket /run/php/php7.4-fpm.sock (*:80)
[Mon Aug 29 09:16:08.819090 2022] [proxy:debug] [pid 1372190:tid 140384978421504] proxy_util.c(2819): [client 104.28.40.15:11869] AH00947: connected /var/www/ndxzstudio/index.php to httpd-UDS:0, referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.818956 2022] [proxy:debug] [pid 1372190:tid 140384978421504] proxy_util.c(2632): [client 104.28.40.15:11869] AH02545: fcgi: has determined UDS as /run/php/php7.4-fpm.sock, referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.818941 2022] [proxy:debug] [pid 1372190:tid 140384978421504] proxy_util.c(2596): [client 104.28.40.15:11869] AH00944: connecting fcgi://localhost/var/www/ndxzstudio/index.php to localhost:8000, referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.818924 2022] [proxy:debug] [pid 1372190:tid 140384978421504] proxy_util.c(2538): AH00942: FCGI: has acquired connection for (*:80)
[Mon Aug 29 09:16:08.818909 2022] [proxy_fcgi:debug] [pid 1372190:tid 140384978421504] mod_proxy_fcgi.c(1063): [client 104.28.40.15:11869] AH01078: serving URL fcgi://localhost/var/www/ndxzstudio/index.php, referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.818894 2022] [proxy_fcgi:debug] [pid 1372190:tid 140384978421504] mod_proxy_fcgi.c(1054): [client 104.28.40.15:11869] AH01076: url: fcgi://localhost/var/www/ndxzstudio/index.php proxyname: (null) proxyport: 0, referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.818871 2022] [proxy:debug] [pid 1372190:tid 140384978421504] mod_proxy.c(1503): [client 104.28.40.15:11869] AH01143: Running scheme unix handler (attempt 0), referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.818819 2022] [authz_core:debug] [pid 1372190:tid 140384978421504] mod_authz_core.c(815): [client 104.28.40.15:11869] AH01626: authorization result of <RequireAny>: granted, referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.818792 2022] [authz_core:debug] [pid 1372190:tid 140384978421504] mod_authz_core.c(815): [client 104.28.40.15:11869] AH01626: authorization result of Require all granted: granted, referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.818337 2022] [authz_core:debug] [pid 1372190:tid 140384978421504] mod_authz_core.c(815): [client 104.28.40.15:11869] AH01626: authorization result of <RequireAny>: granted, referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.818307 2022] [authz_core:debug] [pid 1372190:tid 140384978421504] mod_authz_core.c(815): [client 104.28.40.15:11869] AH01626: authorization result of Require all granted: granted, referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.818145 2022] [ssl:debug] [pid 1372190:tid 140384978421504] ssl_engine_kernel.c(415): [client 104.28.40.15:11869] AH02034: Subsequent (No.3) HTTPS request received for child 38400 (server matthewoliver.com:443), referer: https://matthewoliver.com/ndxzstudio/?a=exhibits&q=edit&id=53
[Mon Aug 29 09:16:08.817931 2022] [http2:debug] [pid 1372190:tid 140383153551104] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,1): recv FRAME[HEADERS[length=125, hend=1, stream=17, eos=1]], frames=126/62 (r/s)
[Mon Aug 29 09:16:08.817848 2022] [http2:debug] [pid 1372190:tid 140383153551104] h2_session.c(1700): [client 104.28.40.15:11869] AH03078: h2_session(149,BUSY,1): transit [IDLE] -- stream change --> [BUSY]
[Mon Aug 29 09:16:08.817806 2022] [http2:debug] [pid 1372190:tid 140383153551104] h2_stream.c(542): [client 104.28.40.15:11869] AH03082: h2_stream(149-17,IDLE): created
[Mon Aug 29 09:16:08.718213 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1700): [client 104.28.40.15:11869] AH03078: h2_session(149,IDLE,0): transit [BUSY] -- no io (keepalive) --> [IDLE]
[Mon Aug 29 09:16:08.718144 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_bucket_beam.c(1282): [client 104.28.40.15:11869] beam(149-9,output,closed=1,aborted=1,empty=1,buf=0): AH03385: h2_task_destroy, reuse secondary
[Mon Aug 29 09:16:08.718043 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,1): sent FRAME[DATA[length=134, flags=1, stream=9, padlen=0]], frames=126/62 (r/s)
[Mon Aug 29 09:16:08.718017 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,1): sent FRAME[HEADERS[length=169, hend=1, stream=9, eos=0]], frames=126/61 (r/s)
[Mon Aug 29 09:16:08.717989 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1545): [client 104.28.40.15:11869] AH02936: h2_stream(149-9,HALF_CLOSED_REMOTE): resumed
[Mon Aug 29 09:16:08.717950 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1390): [client 104.28.40.15:11869] AH03073: h2_stream(149-9,HALF_CLOSED_REMOTE): submit response 200, REMOTE_WINDOW_SIZE=4194304
[Mon Aug 29 09:16:08.717862 2022] [http2:debug] [pid 1372190:tid 140384978421504] h2_task.c(83): [client 104.28.40.15:11869] AH03348: h2_task(149-9): open output to POST matthewoliver.com /ndxzstudio/?a=system&q=fileupload&id=53
[Mon Aug 29 09:16:08.717791 2022] [proxy:debug] [pid 1372190:tid 140384978421504] proxy_util.c(2554): AH00943: FCGI: has released connection for (*:80)
[Mon Aug 29 09:16:08.707038 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-9,OPEN): DATA, len=0, flags=1
[Mon Aug 29 09:16:08.707020 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,1): recv FRAME[DATA[length=0, flags=1, stream=9, padlen=0]], frames=125/60 (r/s)
[Mon Aug 29 09:16:08.706986 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-9,OPEN): DATA, len=14599, flags=0
[Mon Aug 29 09:16:08.706955 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,1): recv FRAME[DATA[length=14599, flags=0, stream=9, padlen=0]], frames=124/60 (r/s)
[Mon Aug 29 09:16:08.695502 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_bucket_beam.c(1282): [client 104.28.40.15:11869] beam(149-15,output,closed=1,aborted=1,empty=1,buf=0): AH03385: h2_task_destroy, reuse secondary
[Mon Aug 29 09:16:08.695403 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,2): sent FRAME[DATA[length=134, flags=1, stream=15, padlen=0]], frames=124/60 (r/s)
[Mon Aug 29 09:16:08.695378 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,2): sent FRAME[HEADERS[length=169, hend=1, stream=15, eos=0]], frames=124/59 (r/s)
[Mon Aug 29 09:16:08.695351 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1545): [client 104.28.40.15:11869] AH02936: h2_stream(149-15,HALF_CLOSED_REMOTE): resumed
[Mon Aug 29 09:16:08.695306 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1390): [client 104.28.40.15:11869] AH03073: h2_stream(149-15,HALF_CLOSED_REMOTE): submit response 200, REMOTE_WINDOW_SIZE=4194304
[Mon Aug 29 09:16:08.695238 2022] [http2:debug] [pid 1372190:tid 140384986822400] h2_task.c(83): [client 104.28.40.15:11869] AH03348: h2_task(149-15): open output to POST matthewoliver.com /ndxzstudio/?a=system&q=fileupload&id=53
[Mon Aug 29 09:16:08.695193 2022] [proxy:debug] [pid 1372190:tid 140384986822400] proxy_util.c(2554): AH00943: FCGI: has released connection for (*:80)
[Mon Aug 29 09:16:08.691667 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,2): sent FRAME[WINDOW_UPDATE[stream=15, incr=46915]], frames=124/58 (r/s)
[Mon Aug 29 09:16:08.691463 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-15,OPEN): DATA, len=0, flags=1
[Mon Aug 29 09:16:08.691436 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,2): recv FRAME[DATA[length=0, flags=1, stream=15, padlen=0]], frames=123/57 (r/s)
[Mon Aug 29 09:16:08.691390 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-15,OPEN): DATA, len=14147, flags=0
[Mon Aug 29 09:16:08.691362 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,2): recv FRAME[DATA[length=14147, flags=0, stream=15, padlen=0]], frames=122/57 (r/s)
[Mon Aug 29 09:16:08.691318 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-15,OPEN): DATA, len=16384, flags=0
[Mon Aug 29 09:16:08.691274 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,2): recv FRAME[DATA[length=16384, flags=0, stream=15, padlen=0]], frames=121/57 (r/s)
[Mon Aug 29 09:16:08.648389 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-15,OPEN): DATA, len=16384, flags=0
[Mon Aug 29 09:16:08.648337 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,2): recv FRAME[DATA[length=16384, flags=0, stream=15, padlen=0]], frames=120/57 (r/s)
[Mon Aug 29 09:16:08.599250 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_bucket_beam.c(1282): [client 104.28.40.15:11869] beam(149-13,output,closed=1,aborted=1,empty=1,buf=0): AH03385: h2_task_destroy, reuse secondary
[Mon Aug 29 09:16:08.599166 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,3): sent FRAME[DATA[length=134, flags=1, stream=13, padlen=0]], frames=120/57 (r/s)
[Mon Aug 29 09:16:08.599141 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,3): sent FRAME[HEADERS[length=169, hend=1, stream=13, eos=0]], frames=120/56 (r/s)
[Mon Aug 29 09:16:08.599114 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1545): [client 104.28.40.15:11869] AH02936: h2_stream(149-13,HALF_CLOSED_REMOTE): resumed
[Mon Aug 29 09:16:08.599077 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1390): [client 104.28.40.15:11869] AH03073: h2_stream(149-13,HALF_CLOSED_REMOTE): submit response 200, REMOTE_WINDOW_SIZE=4194304
[Mon Aug 29 09:16:08.598950 2022] [http2:debug] [pid 1372190:tid 140385020393216] h2_task.c(83): [client 104.28.40.15:11869] AH03348: h2_task(149-13): open output to POST matthewoliver.com /ndxzstudio/?a=system&q=fileupload&id=53
[Mon Aug 29 09:16:08.598905 2022] [proxy:debug] [pid 1372190:tid 140385020393216] proxy_util.c(2554): AH00943: FCGI: has released connection for (*:80)
[Mon Aug 29 09:16:08.595111 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,3): sent FRAME[WINDOW_UPDATE[stream=13, incr=34474]], frames=120/55 (r/s)
[Mon Aug 29 09:16:08.595035 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-13,OPEN): DATA, len=0, flags=1
[Mon Aug 29 09:16:08.595008 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,3): recv FRAME[DATA[length=0, flags=1, stream=13, padlen=0]], frames=119/54 (r/s)
[Mon Aug 29 09:16:08.594961 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-13,OPEN): DATA, len=1706, flags=0
[Mon Aug 29 09:16:08.594935 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,3): recv FRAME[DATA[length=1706, flags=0, stream=13, padlen=0]], frames=118/54 (r/s)
[Mon Aug 29 09:16:08.594906 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-13,OPEN): DATA, len=16384, flags=0
[Mon Aug 29 09:16:08.594876 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,3): recv FRAME[DATA[length=16384, flags=0, stream=13, padlen=0]], frames=117/54 (r/s)
[Mon Aug 29 09:16:08.594777 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-13,OPEN): DATA, len=16384, flags=0
[Mon Aug 29 09:16:08.594732 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,3): recv FRAME[DATA[length=16384, flags=0, stream=13, padlen=0]], frames=116/54 (r/s)
[Mon Aug 29 09:16:08.510754 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,3): sent FRAME[WINDOW_UPDATE[stream=9, incr=32767]], frames=116/54 (r/s)
[Mon Aug 29 09:16:08.510577 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-9,OPEN): DATA, len=16383, flags=0
[Mon Aug 29 09:16:08.510548 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,3): recv FRAME[DATA[length=16383, flags=0, stream=9, padlen=0]], frames=115/53 (r/s)
[Mon Aug 29 09:16:08.510483 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-9,OPEN): DATA, len=16384, flags=0
[Mon Aug 29 09:16:08.510437 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,3): recv FRAME[DATA[length=16384, flags=0, stream=9, padlen=0]], frames=114/53 (r/s)
[Mon Aug 29 09:16:08.466625 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_bucket_beam.c(1282): [client 104.28.40.15:11869] beam(149-11,output,closed=1,aborted=1,empty=1,buf=0): AH03385: h2_task_destroy, reuse secondary
[Mon Aug 29 09:16:08.466541 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,4): sent FRAME[DATA[length=134, flags=1, stream=11, padlen=0]], frames=114/53 (r/s)
[Mon Aug 29 09:16:08.466517 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,4): sent FRAME[HEADERS[length=169, hend=1, stream=11, eos=0]], frames=114/52 (r/s)
[Mon Aug 29 09:16:08.466489 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1545): [client 104.28.40.15:11869] AH02936: h2_stream(149-11,HALF_CLOSED_REMOTE): resumed
[Mon Aug 29 09:16:08.466451 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1390): [client 104.28.40.15:11869] AH03073: h2_stream(149-11,HALF_CLOSED_REMOTE): submit response 200, REMOTE_WINDOW_SIZE=4194304
[Mon Aug 29 09:16:08.466349 2022] [http2:debug] [pid 1372190:tid 140385012000512] h2_task.c(83): [client 104.28.40.15:11869] AH03348: h2_task(149-11): open output to POST matthewoliver.com /ndxzstudio/?a=system&q=fileupload&id=53
[Mon Aug 29 09:16:08.466304 2022] [proxy:debug] [pid 1372190:tid 140385012000512] proxy_util.c(2554): AH00943: FCGI: has released connection for (*:80)
[Mon Aug 29 09:16:08.462689 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-11,OPEN): DATA, len=0, flags=1
[Mon Aug 29 09:16:08.462661 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,4): recv FRAME[DATA[length=0, flags=1, stream=11, padlen=0]], frames=113/51 (r/s)
[Mon Aug 29 09:16:08.462614 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-11,OPEN): DATA, len=6813, flags=0
[Mon Aug 29 09:16:08.462589 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,4): recv FRAME[DATA[length=6813, flags=0, stream=11, padlen=0]], frames=112/51 (r/s)
[Mon Aug 29 09:16:08.462558 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-11,OPEN): DATA, len=16384, flags=0
[Mon Aug 29 09:16:08.462510 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,4): recv FRAME[DATA[length=16384, flags=0, stream=11, padlen=0]], frames=111/51 (r/s)
[Mon Aug 29 09:16:08.436960 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_bucket_beam.c(1282): [client 104.28.40.15:11869] beam(149-3,output,closed=1,aborted=1,empty=1,buf=0): AH03385: h2_task_destroy, reuse secondary
[Mon Aug 29 09:16:08.436848 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,4): sent FRAME[WINDOW_UPDATE[stream=9, incr=32768]], frames=111/51 (r/s)
[Mon Aug 29 09:16:08.436815 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,5): sent FRAME[DATA[length=134, flags=1, stream=3, padlen=0]], frames=111/50 (r/s)
[Mon Aug 29 09:16:08.436715 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(591): [client 104.28.40.15:11869] AH03068: h2_session(149,BUSY,5): sent FRAME[HEADERS[length=169, hend=1, stream=3, eos=0]], frames=111/49 (r/s)
[Mon Aug 29 09:16:08.436679 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1545): [client 104.28.40.15:11869] AH02936: h2_stream(149-3,HALF_CLOSED_REMOTE): resumed
[Mon Aug 29 09:16:08.436635 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(1390): [client 104.28.40.15:11869] AH03073: h2_stream(149-3,HALF_CLOSED_REMOTE): submit response 200, REMOTE_WINDOW_SIZE=4194304
[Mon Aug 29 09:16:08.436554 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-3,OPEN): DATA, len=0, flags=1
[Mon Aug 29 09:16:08.436525 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,5): recv FRAME[DATA[length=0, flags=1, stream=3, padlen=0]], frames=110/48 (r/s)
[Mon Aug 29 09:16:08.436476 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-9,OPEN): DATA, len=16384, flags=0
[Mon Aug 29 09:16:08.436441 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(339): [client 104.28.40.15:11869] AH03066: h2_session(149,BUSY,5): recv FRAME[DATA[length=16384, flags=0, stream=9, padlen=0]], frames=109/48 (r/s)
[Mon Aug 29 09:16:08.436138 2022] [http2:debug] [pid 1372190:tid 140385028785920] h2_task.c(83): [client 104.28.40.15:11869] AH03348: h2_task(149-3): open output to POST matthewoliver.com /ndxzstudio/?a=system&q=fileupload&id=53
[Mon Aug 29 09:16:08.436057 2022] [proxy:debug] [pid 1372190:tid 140385028785920] proxy_util.c(2554): AH00943: FCGI: has released connection for (*:80)
[Mon Aug 29 09:16:08.425452 2022] [http2:debug] [pid 1372190:tid 140383287768832] h2_session.c(361): [client 104.28.40.15:11869] AH02923: h2_stream(149-3,OPEN): DATA, len=15016, flags=0
`

**Comment by Vaska** [comment]
Just gave it a test and it's fine. Update your PHP to the newest version possible to keep things as current.

**Comment by HazMatt69** [comment]
Ok, unfortunately I still need php7.4 for an app... I will try and run multiple php versions!

**Comment by HazMatt69** [comment]
Quick update:
I've installed php8.1. I still get an "upload error abort". Files I'm trying to upload are 150 to 225kb. (options.php is set to 500kb). I notice that when error abort appears, file size always says 114.69KB.

**Comment by Vaska** [comment]
And this is a shared web host server or your own setup (I simply can not support local server setups)? I haven't had any other reports of this - it's not something I'm going to look further into unless I have more reports.

**Comment by HazMatt69** [comment]
Yeah, this is probably a problem on my side (it is my own server...). Just asked in case someone else was having the same issue. Thanks anyways!
