### ISSUE TITLE
Apparent error in 2.1.6 upgrade script

### ISSUE THREAD

**Issue by universalhandle** [Indexhibit/indexhibit#39]
I finally got around to upgrading PHP on my server, and the Indexhibit site I host gave me a surprising amount of trouble. After some debugging, I determined that this line https://github.com/Indexhibit/indexhibit/commit/132f45d07a29bc39a3bda519198cb33dcc529996#diff-4d18d0309652c2b2b099d0e65e1894d6f0d00869e599931b29c8261061100f90R16 was causing 500 errors. It produces the following SQL:

```sql
UPDATE ndxz_users SET ID = '1' WHERE user_admin = '1';
```

... which has the effect of setting to 1 the user ID of any user who has been granted admin privileges. This results in the following error:

```
ERROR 1062 (23000): Duplicate entry '1' for key 'ndxz_users.PRIMARY'
```

From the "Admin Status" field on the User page, it seems the intended design is to allow multiple users to be admins.

I'm not sure what the intent was in adding this upgrade step, but instances with multiple admins can simply comment out that line before running the upgrade to work around the problem.

**Comment by Indexhibit** [comment]
Oh my, some of the things that have not been noticed for ages - I was not aware of this error. I'll fix it shortly. Years ago I noticed many people were disabling their admin rights accidentally (another bug) and so I added that to make/keep the primary user an admin (kind of a super admin). I'm unsure if I should remove it completely (instead of fixing it). People are going 15 years now without upgrading (a bit frustrating to be honest but if it works that's great, I guess).

**Comment by universalhandle** [comment]
My two cents: addressing the accidental self-removal of admin rights in an upgrade step seems misplaced unless it was a widespread issue introduced in a specific release (e.g., a different database upgrade caused it, or it was impossible to submit the user form without de-adminning). I'd remove it completely, myself.

For lockouts caused by user error, a twist on the [password reset utility](https://forum.indexhibit.org/util/password-reset-v2/) seems more appropriate. Accidentally disabling de-escalating your privileges is basically a variation of the same problem: the user goofed their login somehow, and now we have to resort to extreme measures to regain access.

Even in the examples I presented, though, the fix seems somehow simultaneously too broad and too narrow. It's too broad in that it assumes that the user who installed Indexhibit is and will always be a trusted user. It's too narrow in that if the de-adminning problem affected any user besides 1, it doesn't restore their access.

In some respects, including this script in an upgrade step represents a low-grade security risk. Suppose I intentionally took away user 1's admin privileges, then upgraded the instance. This upgrade step would silently re-escalate their privileges.
