### ISSUE TITLE
Redirects to HTTPS even though webhost doesn't support

### ISSUE THREAD

**Issue by hongkonggong** [Indexhibit/indexhibit#9]
Hi! Line 32 of ndxzstudio/defaults.php was giving me trouble in my installation and kept redirecting me to the HTTPS version of my site even though one hadn't been set up/my webhost was not supporting it. Am on webfaction and have resolved the issue manually by force setting line 32 to 'http'.

\o/

**Comment by Vaska** [comment]
I believe your hosting is not standard shared hosting - which is what Indexhibit is optimized for. Plus, how can they not support https? We are supposed to be using that - and you should be using it. I'm happy you have made a quick resolution for this, but I don't see this as something we should address. I'm going to mark this closed (this should have been posted to our forum). Cheers

**Comment by hongkonggong** [comment]
Well technically the webhost supports HTTPS but I didn't have it turned on this for because I don't have an easy SSL certificate solution yet (Let's Encrypt still not automated enough). Just wanted to raise the issue because I've not had this problem on this host before on any of the other CMS's I've used (Wordpress, Kirby, Stacey, Ghost). Anyway, thanks for getting back to me. Appreciate it.

**Comment by Vaska** [comment]
It seems that it is turned on though otherwise it would not be triggering https (Indexhibit works with both). It's the first time I've ever heard of a problem having this issue, as well.

**Comment by hongkonggong** [comment]
Yeah that's what I got from the code, not sure why it was triggering it. But if I'm the only one with this problem feel free to ignore me :) Thanks again and keep up the good work!

**Comment by Vaska** [comment]
haha...i'm not going to ignore you. honestly though, i feel something else is triggering this. anyways, you made a quick edit and progress moves forward...that's always good.
